//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public Articulo()
        {
            this.Articulo_Compra = new HashSet<Articulo_Compra>();
        }
    
        public int ID_Articulo { get; set; }
        public int Precio_ID_Precio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public int Tipo_Articulo_ID_TipoArt { get; set; }
        public string Imagen { get; set; }
    
        public virtual ICollection<Articulo_Compra> Articulo_Compra { get; set; }
        public virtual Precio Precio { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo { get; set; }
    }
}
