//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo_Compra
    {
        public int Articulo_ID_Articulo { get; set; }
        public int Compra_ID_Compra { get; set; }
        public int Cantidad_Comprada { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
