//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public string Cedula { get; set; }
        public int EstadoCliente_ID_EstadoCli { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
    
        public virtual EstadoCliente EstadoCliente { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
