//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.Actividad_Compra = new HashSet<Actividad_Compra>();
            this.Articulo_Compra = new HashSet<Articulo_Compra>();
        }
    
        public int ID_Compra { get; set; }
        public int Reserva_ID_Reserva { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<Actividad_Compra> Actividad_Compra { get; set; }
        public virtual ICollection<Articulo_Compra> Articulo_Compra { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
