//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        public int ID_Consecutivo { get; set; }
        public string Descripcion { get; set; }
        public int Num_Consecutivo { get; set; }
        public bool Posee_Prefijo { get; set; }
        public string Prefijo { get; set; }
        public bool Posee_Rango { get; set; }
        public Nullable<int> Rango_Inicial { get; set; }
        public Nullable<int> Rango_Final { get; set; }
    }
}
