//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyPay
    {
        public string CorreoCuenta { get; set; }
        public int CodSeguridad { get; set; }
        public string Contrasena { get; set; }
        public decimal NumTarjeta { get; set; }
    
        public virtual SB_Tarjeta SB_Tarjeta { get; set; }
    }
}
