//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCliente
    {
        public EstadoCliente()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int ID_EstadoCli { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
