//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HotelesEntities : DbContext
    {
        public HotelesEntities()
            : base("name=HotelesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividad> Actividads { get; set; }
        public DbSet<Actividad_Compra> Actividad_Compra { get; set; }
        public DbSet<Articulo> Articuloes { get; set; }
        public DbSet<Articulo_Compra> Articulo_Compra { get; set; }
        public DbSet<Bitacora> Bitacoras { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Compra> Compras { get; set; }
        public DbSet<Consecutivo> Consecutivoes { get; set; }
        public DbSet<EasyPay> EasyPays { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<EstadoCliente> EstadoClientes { get; set; }
        public DbSet<EstadoHabitacion> EstadoHabitacions { get; set; }
        public DbSet<EstadoReserva> EstadoReservas { get; set; }
        public DbSet<Habitacion> Habitacions { get; set; }
        public DbSet<Precio> Precios { get; set; }
        public DbSet<Reserva> Reservas { get; set; }
        public DbSet<Rol> Rols { get; set; }
        public DbSet<Rol_Usuario> Rol_Usuario { get; set; }
        public DbSet<SB_Tarjeta> SB_Tarjeta { get; set; }
        public DbSet<Tarjeta> Tarjetas { get; set; }
        public DbSet<Tipo_Articulo> Tipo_Articulo { get; set; }
        public DbSet<Tipo_Habitacion> Tipo_Habitacion { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sproc_hoteles_CambiarContrasena(string cedula, string contrasena, string nuevaContrasena)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var nuevaContrasenaParameter = nuevaContrasena != null ?
                new ObjectParameter("NuevaContrasena", nuevaContrasena) :
                new ObjectParameter("NuevaContrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_hoteles_CambiarContrasena", cedulaParameter, contrasenaParameter, nuevaContrasenaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteActividad(Nullable<int> iD_Actividad)
        {
            var iD_ActividadParameter = iD_Actividad.HasValue ?
                new ObjectParameter("ID_Actividad", iD_Actividad) :
                new ObjectParameter("ID_Actividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteActividad", iD_ActividadParameter);
        }
    
        public virtual int sproc_hoteles_DeleteActividad_Compra(Nullable<int> actividad_ID_Actividad, Nullable<int> compra_ID_Compra)
        {
            var actividad_ID_ActividadParameter = actividad_ID_Actividad.HasValue ?
                new ObjectParameter("Actividad_ID_Actividad", actividad_ID_Actividad) :
                new ObjectParameter("Actividad_ID_Actividad", typeof(int));
    
            var compra_ID_CompraParameter = compra_ID_Compra.HasValue ?
                new ObjectParameter("Compra_ID_Compra", compra_ID_Compra) :
                new ObjectParameter("Compra_ID_Compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteActividad_Compra", actividad_ID_ActividadParameter, compra_ID_CompraParameter);
        }
    
        public virtual int sproc_hoteles_DeleteArticulo(Nullable<int> iD_Articulo)
        {
            var iD_ArticuloParameter = iD_Articulo.HasValue ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteArticulo", iD_ArticuloParameter);
        }
    
        public virtual int sproc_hoteles_DeleteArticulo_Compra(Nullable<int> articulo_ID_Articulo, Nullable<int> compra_ID_Compra)
        {
            var articulo_ID_ArticuloParameter = articulo_ID_Articulo.HasValue ?
                new ObjectParameter("Articulo_ID_Articulo", articulo_ID_Articulo) :
                new ObjectParameter("Articulo_ID_Articulo", typeof(int));
    
            var compra_ID_CompraParameter = compra_ID_Compra.HasValue ?
                new ObjectParameter("Compra_ID_Compra", compra_ID_Compra) :
                new ObjectParameter("Compra_ID_Compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteArticulo_Compra", articulo_ID_ArticuloParameter, compra_ID_CompraParameter);
        }
    
        public virtual int sproc_hoteles_DeleteBitacora(Nullable<int> iD_Cambio)
        {
            var iD_CambioParameter = iD_Cambio.HasValue ?
                new ObjectParameter("ID_Cambio", iD_Cambio) :
                new ObjectParameter("ID_Cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteBitacora", iD_CambioParameter);
        }
    
        public virtual int sproc_hoteles_DeleteCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteCliente", cedulaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteCompra(Nullable<int> iD_Compra)
        {
            var iD_CompraParameter = iD_Compra.HasValue ?
                new ObjectParameter("ID_Compra", iD_Compra) :
                new ObjectParameter("ID_Compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteCompra", iD_CompraParameter);
        }
    
        public virtual int sproc_hoteles_DeleteConsecutivo(Nullable<int> iD_Consecutivo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteConsecutivo", iD_ConsecutivoParameter);
        }
    
        public virtual int sproc_hoteles_DeleteEasyPay(string correoCuenta)
        {
            var correoCuentaParameter = correoCuenta != null ?
                new ObjectParameter("CorreoCuenta", correoCuenta) :
                new ObjectParameter("CorreoCuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteEasyPay", correoCuentaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteError(Nullable<int> iD_Error)
        {
            var iD_ErrorParameter = iD_Error.HasValue ?
                new ObjectParameter("ID_Error", iD_Error) :
                new ObjectParameter("ID_Error", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteError", iD_ErrorParameter);
        }
    
        public virtual int sproc_hoteles_DeleteEstadoCliente(Nullable<int> iD_EstadoCli)
        {
            var iD_EstadoCliParameter = iD_EstadoCli.HasValue ?
                new ObjectParameter("ID_EstadoCli", iD_EstadoCli) :
                new ObjectParameter("ID_EstadoCli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteEstadoCliente", iD_EstadoCliParameter);
        }
    
        public virtual int sproc_hoteles_DeleteEstadoHabitacion(string iD_EstadoHab)
        {
            var iD_EstadoHabParameter = iD_EstadoHab != null ?
                new ObjectParameter("ID_EstadoHab", iD_EstadoHab) :
                new ObjectParameter("ID_EstadoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteEstadoHabitacion", iD_EstadoHabParameter);
        }
    
        public virtual int sproc_hoteles_DeleteEstadoReserva(Nullable<int> iD_EstadoRes)
        {
            var iD_EstadoResParameter = iD_EstadoRes.HasValue ?
                new ObjectParameter("ID_EstadoRes", iD_EstadoRes) :
                new ObjectParameter("ID_EstadoRes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteEstadoReserva", iD_EstadoResParameter);
        }
    
        public virtual int sproc_hoteles_DeleteHabitacion(Nullable<int> iD_Habitacion)
        {
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteHabitacion", iD_HabitacionParameter);
        }
    
        public virtual int sproc_hoteles_DeletePrecio(Nullable<int> iD_Precio)
        {
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeletePrecio", iD_PrecioParameter);
        }
    
        public virtual int sproc_hoteles_DeleteReserva(Nullable<int> iD_Reserva)
        {
            var iD_ReservaParameter = iD_Reserva.HasValue ?
                new ObjectParameter("ID_Reserva", iD_Reserva) :
                new ObjectParameter("ID_Reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteReserva", iD_ReservaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteReserva_Habitacion(Nullable<int> reserva_ID_Reserva, Nullable<int> habitacion_ID_Habitacion)
        {
            var reserva_ID_ReservaParameter = reserva_ID_Reserva.HasValue ?
                new ObjectParameter("Reserva_ID_Reserva", reserva_ID_Reserva) :
                new ObjectParameter("Reserva_ID_Reserva", typeof(int));
    
            var habitacion_ID_HabitacionParameter = habitacion_ID_Habitacion.HasValue ?
                new ObjectParameter("Habitacion_ID_Habitacion", habitacion_ID_Habitacion) :
                new ObjectParameter("Habitacion_ID_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteReserva_Habitacion", reserva_ID_ReservaParameter, habitacion_ID_HabitacionParameter);
        }
    
        public virtual int sproc_hoteles_DeleteRol(Nullable<int> iD_Rol)
        {
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteRol", iD_RolParameter);
        }
    
        public virtual int sproc_hoteles_DeleteRol_Usuario(string usuario_Cedula)
        {
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteRol_Usuario", usuario_CedulaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteSB_Tarjeta(Nullable<decimal> numTarjeta)
        {
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteSB_Tarjeta", numTarjetaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteTarjeta(string num_Tarjeta)
        {
            var num_TarjetaParameter = num_Tarjeta != null ?
                new ObjectParameter("Num_Tarjeta", num_Tarjeta) :
                new ObjectParameter("Num_Tarjeta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteTarjeta", num_TarjetaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteTarjeta_Cliente(string cliente_Cedula)
        {
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteTarjeta_Cliente", cliente_CedulaParameter);
        }
    
        public virtual int sproc_hoteles_DeleteTipo_Articulo(Nullable<int> iD_TipoArt)
        {
            var iD_TipoArtParameter = iD_TipoArt.HasValue ?
                new ObjectParameter("ID_TipoArt", iD_TipoArt) :
                new ObjectParameter("ID_TipoArt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteTipo_Articulo", iD_TipoArtParameter);
        }
    
        public virtual int sproc_hoteles_DeleteTipo_Habitacion(string iD_TipoHab)
        {
            var iD_TipoHabParameter = iD_TipoHab != null ?
                new ObjectParameter("ID_TipoHab", iD_TipoHab) :
                new ObjectParameter("ID_TipoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteTipo_Habitacion", iD_TipoHabParameter);
        }
    
        public virtual int sproc_hoteles_DeleteUsuario(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_DeleteUsuario", cedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetActividad_Result> sproc_hoteles_GetActividad(Nullable<int> iD_Actividad)
        {
            var iD_ActividadParameter = iD_Actividad.HasValue ?
                new ObjectParameter("ID_Actividad", iD_Actividad) :
                new ObjectParameter("ID_Actividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetActividad_Result>("sproc_hoteles_GetActividad", iD_ActividadParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetActividadList_Result> sproc_hoteles_GetActividadList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetActividadList_Result>("sproc_hoteles_GetActividadList");
        }
    
        public virtual ObjectResult<sproc_hoteles_GetArticulo_Result> sproc_hoteles_GetArticulo(string iD_Articulo)
        {
            var iD_ArticuloParameter = iD_Articulo != null ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetArticulo_Result>("sproc_hoteles_GetArticulo", iD_ArticuloParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetArticuloList_Result> sproc_hoteles_GetArticuloList(string iD_Articulo)
        {
            var iD_ArticuloParameter = iD_Articulo != null ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetArticuloList_Result>("sproc_hoteles_GetArticuloList", iD_ArticuloParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetBitacora_Result> sproc_hoteles_GetBitacora(Nullable<int> iD_Cambio)
        {
            var iD_CambioParameter = iD_Cambio.HasValue ?
                new ObjectParameter("ID_Cambio", iD_Cambio) :
                new ObjectParameter("ID_Cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetBitacora_Result>("sproc_hoteles_GetBitacora", iD_CambioParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetBitacoraList_Result> sproc_hoteles_GetBitacoraList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetBitacoraList_Result>("sproc_hoteles_GetBitacoraList");
        }
    
        public virtual ObjectResult<sproc_hoteles_GetCliente_Result> sproc_hoteles_GetCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetCliente_Result>("sproc_hoteles_GetCliente", cedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetClienteList_Result> sproc_hoteles_GetClienteList(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetClienteList_Result>("sproc_hoteles_GetClienteList", cedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetConsecutivo_Result> sproc_hoteles_GetConsecutivo(Nullable<int> iD_Consecutivo)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetConsecutivo_Result>("sproc_hoteles_GetConsecutivo", iD_ConsecutivoParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetConsecutivoList_Result> sproc_hoteles_GetConsecutivoList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetConsecutivoList_Result>("sproc_hoteles_GetConsecutivoList");
        }
    
        public virtual ObjectResult<sproc_hoteles_GetDataBitacora_Result> sproc_hoteles_GetDataBitacora(string usuario, Nullable<System.DateTime> fecha, string tipo)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetDataBitacora_Result>("sproc_hoteles_GetDataBitacora", usuarioParameter, fechaParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEasyPay_Result> sproc_hoteles_GetEasyPay(string correoCuenta)
        {
            var correoCuentaParameter = correoCuenta != null ?
                new ObjectParameter("CorreoCuenta", correoCuenta) :
                new ObjectParameter("CorreoCuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEasyPay_Result>("sproc_hoteles_GetEasyPay", correoCuentaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEasyPayList_Result> sproc_hoteles_GetEasyPayList(string correoCuenta)
        {
            var correoCuentaParameter = correoCuenta != null ?
                new ObjectParameter("CorreoCuenta", correoCuenta) :
                new ObjectParameter("CorreoCuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEasyPayList_Result>("sproc_hoteles_GetEasyPayList", correoCuentaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetError_Result> sproc_hoteles_GetError(Nullable<int> iD_Error)
        {
            var iD_ErrorParameter = iD_Error.HasValue ?
                new ObjectParameter("ID_Error", iD_Error) :
                new ObjectParameter("ID_Error", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetError_Result>("sproc_hoteles_GetError", iD_ErrorParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetErrorList_Result> sproc_hoteles_GetErrorList(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetErrorList_Result>("sproc_hoteles_GetErrorList", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoCliente_Result> sproc_hoteles_GetEstadoCliente(Nullable<int> iD_EstadoCli)
        {
            var iD_EstadoCliParameter = iD_EstadoCli.HasValue ?
                new ObjectParameter("ID_EstadoCli", iD_EstadoCli) :
                new ObjectParameter("ID_EstadoCli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoCliente_Result>("sproc_hoteles_GetEstadoCliente", iD_EstadoCliParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoClienteList_Result> sproc_hoteles_GetEstadoClienteList(Nullable<int> iD_EstadoCli)
        {
            var iD_EstadoCliParameter = iD_EstadoCli.HasValue ?
                new ObjectParameter("ID_EstadoCli", iD_EstadoCli) :
                new ObjectParameter("ID_EstadoCli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoClienteList_Result>("sproc_hoteles_GetEstadoClienteList", iD_EstadoCliParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoHabitacion_Result> sproc_hoteles_GetEstadoHabitacion(string iD_EstadoHab)
        {
            var iD_EstadoHabParameter = iD_EstadoHab != null ?
                new ObjectParameter("ID_EstadoHab", iD_EstadoHab) :
                new ObjectParameter("ID_EstadoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoHabitacion_Result>("sproc_hoteles_GetEstadoHabitacion", iD_EstadoHabParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoHabitacionList_Result> sproc_hoteles_GetEstadoHabitacionList(string iD_EstadoHab)
        {
            var iD_EstadoHabParameter = iD_EstadoHab != null ?
                new ObjectParameter("ID_EstadoHab", iD_EstadoHab) :
                new ObjectParameter("ID_EstadoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoHabitacionList_Result>("sproc_hoteles_GetEstadoHabitacionList", iD_EstadoHabParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoReserva_Result> sproc_hoteles_GetEstadoReserva(Nullable<int> iD_EstadoRes)
        {
            var iD_EstadoResParameter = iD_EstadoRes.HasValue ?
                new ObjectParameter("ID_EstadoRes", iD_EstadoRes) :
                new ObjectParameter("ID_EstadoRes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoReserva_Result>("sproc_hoteles_GetEstadoReserva", iD_EstadoResParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetEstadoReservaList_Result> sproc_hoteles_GetEstadoReservaList(Nullable<int> iD_EstadoRes)
        {
            var iD_EstadoResParameter = iD_EstadoRes.HasValue ?
                new ObjectParameter("ID_EstadoRes", iD_EstadoRes) :
                new ObjectParameter("ID_EstadoRes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetEstadoReservaList_Result>("sproc_hoteles_GetEstadoReservaList", iD_EstadoResParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetHabitacion_Result> sproc_hoteles_GetHabitacion(Nullable<int> iD_Habitacion)
        {
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetHabitacion_Result>("sproc_hoteles_GetHabitacion", iD_HabitacionParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetHabitacionList_Result> sproc_hoteles_GetHabitacionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetHabitacionList_Result>("sproc_hoteles_GetHabitacionList");
        }
    
        public virtual ObjectResult<sproc_hoteles_GetPrecio_Result> sproc_hoteles_GetPrecio(Nullable<int> iD_Precio)
        {
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetPrecio_Result>("sproc_hoteles_GetPrecio", iD_PrecioParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetPrecioList_Result> sproc_hoteles_GetPrecioList(Nullable<int> iD_Precio)
        {
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetPrecioList_Result>("sproc_hoteles_GetPrecioList", iD_PrecioParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetReserva_Result> sproc_hoteles_GetReserva(Nullable<int> iD_Reserva)
        {
            var iD_ReservaParameter = iD_Reserva.HasValue ?
                new ObjectParameter("ID_Reserva", iD_Reserva) :
                new ObjectParameter("ID_Reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetReserva_Result>("sproc_hoteles_GetReserva", iD_ReservaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetReservaList_Result> sproc_hoteles_GetReservaList(Nullable<int> iD_Reserva)
        {
            var iD_ReservaParameter = iD_Reserva.HasValue ?
                new ObjectParameter("ID_Reserva", iD_Reserva) :
                new ObjectParameter("ID_Reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetReservaList_Result>("sproc_hoteles_GetReservaList", iD_ReservaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetRol_Result> sproc_hoteles_GetRol(Nullable<int> iD_Rol)
        {
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetRol_Result>("sproc_hoteles_GetRol", iD_RolParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetRol_Usuario_Result> sproc_hoteles_GetRol_Usuario(Nullable<int> rol_ID_Rol, string usuario_Cedula)
        {
            var rol_ID_RolParameter = rol_ID_Rol.HasValue ?
                new ObjectParameter("Rol_ID_Rol", rol_ID_Rol) :
                new ObjectParameter("Rol_ID_Rol", typeof(int));
    
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetRol_Usuario_Result>("sproc_hoteles_GetRol_Usuario", rol_ID_RolParameter, usuario_CedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetRol_Usuario_Por_Cedula_Result> sproc_hoteles_GetRol_Usuario_Por_Cedula(string usuario_Cedula)
        {
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetRol_Usuario_Por_Cedula_Result>("sproc_hoteles_GetRol_Usuario_Por_Cedula", usuario_CedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetRol_UsuarioList_Result> sproc_hoteles_GetRol_UsuarioList(Nullable<int> rol_ID_Rol, string usuario_Cedula)
        {
            var rol_ID_RolParameter = rol_ID_Rol.HasValue ?
                new ObjectParameter("Rol_ID_Rol", rol_ID_Rol) :
                new ObjectParameter("Rol_ID_Rol", typeof(int));
    
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetRol_UsuarioList_Result>("sproc_hoteles_GetRol_UsuarioList", rol_ID_RolParameter, usuario_CedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetRolList_Result> sproc_hoteles_GetRolList(Nullable<int> iD_Rol)
        {
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetRolList_Result>("sproc_hoteles_GetRolList", iD_RolParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetSB_Tarjeta_Result> sproc_hoteles_GetSB_Tarjeta(Nullable<decimal> numTarjeta)
        {
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetSB_Tarjeta_Result>("sproc_hoteles_GetSB_Tarjeta", numTarjetaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetSB_TarjetaList_Result> sproc_hoteles_GetSB_TarjetaList(Nullable<decimal> numTarjeta)
        {
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetSB_TarjetaList_Result>("sproc_hoteles_GetSB_TarjetaList", numTarjetaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTarjeta_Result> sproc_hoteles_GetTarjeta(string num_Tarjeta)
        {
            var num_TarjetaParameter = num_Tarjeta != null ?
                new ObjectParameter("Num_Tarjeta", num_Tarjeta) :
                new ObjectParameter("Num_Tarjeta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTarjeta_Result>("sproc_hoteles_GetTarjeta", num_TarjetaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTarjeta_Cliente_Result> sproc_hoteles_GetTarjeta_Cliente(string cliente_Cedula)
        {
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTarjeta_Cliente_Result>("sproc_hoteles_GetTarjeta_Cliente", cliente_CedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTarjeta_ClienteList_Result> sproc_hoteles_GetTarjeta_ClienteList(string cliente_Cedula)
        {
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTarjeta_ClienteList_Result>("sproc_hoteles_GetTarjeta_ClienteList", cliente_CedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTarjetaList_Result> sproc_hoteles_GetTarjetaList(string num_Tarjeta)
        {
            var num_TarjetaParameter = num_Tarjeta != null ?
                new ObjectParameter("Num_Tarjeta", num_Tarjeta) :
                new ObjectParameter("Num_Tarjeta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTarjetaList_Result>("sproc_hoteles_GetTarjetaList", num_TarjetaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTipo_Articulo_Result> sproc_hoteles_GetTipo_Articulo(Nullable<int> iD_TipoArt)
        {
            var iD_TipoArtParameter = iD_TipoArt.HasValue ?
                new ObjectParameter("ID_TipoArt", iD_TipoArt) :
                new ObjectParameter("ID_TipoArt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTipo_Articulo_Result>("sproc_hoteles_GetTipo_Articulo", iD_TipoArtParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTipo_ArticuloList_Result> sproc_hoteles_GetTipo_ArticuloList(Nullable<int> iD_TipoArt)
        {
            var iD_TipoArtParameter = iD_TipoArt.HasValue ?
                new ObjectParameter("ID_TipoArt", iD_TipoArt) :
                new ObjectParameter("ID_TipoArt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTipo_ArticuloList_Result>("sproc_hoteles_GetTipo_ArticuloList", iD_TipoArtParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTipo_Habitacion_Result> sproc_hoteles_GetTipo_Habitacion(string iD_TipoHab)
        {
            var iD_TipoHabParameter = iD_TipoHab != null ?
                new ObjectParameter("ID_TipoHab", iD_TipoHab) :
                new ObjectParameter("ID_TipoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTipo_Habitacion_Result>("sproc_hoteles_GetTipo_Habitacion", iD_TipoHabParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetTipo_HabitacionList_Result> sproc_hoteles_GetTipo_HabitacionList(string iD_TipoHab)
        {
            var iD_TipoHabParameter = iD_TipoHab != null ?
                new ObjectParameter("ID_TipoHab", iD_TipoHab) :
                new ObjectParameter("ID_TipoHab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetTipo_HabitacionList_Result>("sproc_hoteles_GetTipo_HabitacionList", iD_TipoHabParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetUsuario_Result> sproc_hoteles_GetUsuario(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetUsuario_Result>("sproc_hoteles_GetUsuario", cedulaParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_GetUsuarios_List_Result> sproc_hoteles_GetUsuarios_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_GetUsuarios_List_Result>("sproc_hoteles_GetUsuarios_List");
        }
    
        public virtual int sproc_hoteles_InsertActividad(string nombre, string descripcion, Nullable<int> cupo, Nullable<int> espaciosDisponibles, string imagen)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var cupoParameter = cupo.HasValue ?
                new ObjectParameter("Cupo", cupo) :
                new ObjectParameter("Cupo", typeof(int));
    
            var espaciosDisponiblesParameter = espaciosDisponibles.HasValue ?
                new ObjectParameter("EspaciosDisponibles", espaciosDisponibles) :
                new ObjectParameter("EspaciosDisponibles", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertActividad", nombreParameter, descripcionParameter, cupoParameter, espaciosDisponiblesParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_InsertArticulo(string nombre, string descripcion, Nullable<int> cantidad, Nullable<int> tipo_Articulo_ID_TipoArt, string imagen)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var tipo_Articulo_ID_TipoArtParameter = tipo_Articulo_ID_TipoArt.HasValue ?
                new ObjectParameter("Tipo_Articulo_ID_TipoArt", tipo_Articulo_ID_TipoArt) :
                new ObjectParameter("Tipo_Articulo_ID_TipoArt", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertArticulo", nombreParameter, descripcionParameter, cantidadParameter, tipo_Articulo_ID_TipoArtParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_InsertBitacora(string usuario_Cedula, Nullable<System.DateTime> fecha, string iD_Registro, string tipo, string descripcion, string detalles)
        {
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var iD_RegistroParameter = iD_Registro != null ?
                new ObjectParameter("ID_Registro", iD_Registro) :
                new ObjectParameter("ID_Registro", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var detallesParameter = detalles != null ?
                new ObjectParameter("Detalles", detalles) :
                new ObjectParameter("Detalles", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertBitacora", usuario_CedulaParameter, fechaParameter, iD_RegistroParameter, tipoParameter, descripcionParameter, detallesParameter);
        }
    
        public virtual int sproc_hoteles_InsertCliente(string cedula, Nullable<int> estadoCliente_ID_EstadoCli, string nombre, string primerApellido, string segundoApellido, string correo, string contrasena)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var estadoCliente_ID_EstadoCliParameter = estadoCliente_ID_EstadoCli.HasValue ?
                new ObjectParameter("EstadoCliente_ID_EstadoCli", estadoCliente_ID_EstadoCli) :
                new ObjectParameter("EstadoCliente_ID_EstadoCli", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertCliente", cedulaParameter, estadoCliente_ID_EstadoCliParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, correoParameter, contrasenaParameter);
        }
    
        public virtual int sproc_hoteles_InsertConsecutivo(Nullable<int> num_Consecutivo, Nullable<bool> posee_Prefijo, string prefijo, string description, Nullable<bool> posee_Rango, Nullable<int> rango_Inicial, Nullable<int> rango_Final)
        {
            var num_ConsecutivoParameter = num_Consecutivo.HasValue ?
                new ObjectParameter("Num_Consecutivo", num_Consecutivo) :
                new ObjectParameter("Num_Consecutivo", typeof(int));
    
            var posee_PrefijoParameter = posee_Prefijo.HasValue ?
                new ObjectParameter("Posee_Prefijo", posee_Prefijo) :
                new ObjectParameter("Posee_Prefijo", typeof(bool));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("Prefijo", prefijo) :
                new ObjectParameter("Prefijo", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var posee_RangoParameter = posee_Rango.HasValue ?
                new ObjectParameter("Posee_Rango", posee_Rango) :
                new ObjectParameter("Posee_Rango", typeof(bool));
    
            var rango_InicialParameter = rango_Inicial.HasValue ?
                new ObjectParameter("Rango_Inicial", rango_Inicial) :
                new ObjectParameter("Rango_Inicial", typeof(int));
    
            var rango_FinalParameter = rango_Final.HasValue ?
                new ObjectParameter("Rango_Final", rango_Final) :
                new ObjectParameter("Rango_Final", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertConsecutivo", num_ConsecutivoParameter, posee_PrefijoParameter, prefijoParameter, descriptionParameter, posee_RangoParameter, rango_InicialParameter, rango_FinalParameter);
        }
    
        public virtual int sproc_hoteles_InsertEasyPay(string correoCuenta, Nullable<int> codSeguridad, string contrasena, Nullable<decimal> numTarjeta)
        {
            var correoCuentaParameter = correoCuenta != null ?
                new ObjectParameter("CorreoCuenta", correoCuenta) :
                new ObjectParameter("CorreoCuenta", typeof(string));
    
            var codSeguridadParameter = codSeguridad.HasValue ?
                new ObjectParameter("CodSeguridad", codSeguridad) :
                new ObjectParameter("CodSeguridad", typeof(int));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertEasyPay", correoCuentaParameter, codSeguridadParameter, contrasenaParameter, numTarjetaParameter);
        }
    
        public virtual int sproc_hoteles_InsertError(Nullable<System.DateTime> fecha, string descripcion)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertError", fechaParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertEstadoCliente(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertEstadoCliente", descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertEstadoHabitacion(string iD_Estadohab, string descripcion)
        {
            var iD_EstadohabParameter = iD_Estadohab != null ?
                new ObjectParameter("ID_Estadohab", iD_Estadohab) :
                new ObjectParameter("ID_Estadohab", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertEstadoHabitacion", iD_EstadohabParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertEstadoReserva(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertEstadoReserva", descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertHabitacion(string estado, string precio, string tipoHabitacion, Nullable<int> cantidadPersonas, Nullable<int> camasIndividuales, Nullable<int> camasMatrimoniales, string observaciones, string imagen)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var precioParameter = precio != null ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(string));
    
            var tipoHabitacionParameter = tipoHabitacion != null ?
                new ObjectParameter("TipoHabitacion", tipoHabitacion) :
                new ObjectParameter("TipoHabitacion", typeof(string));
    
            var cantidadPersonasParameter = cantidadPersonas.HasValue ?
                new ObjectParameter("CantidadPersonas", cantidadPersonas) :
                new ObjectParameter("CantidadPersonas", typeof(int));
    
            var camasIndividualesParameter = camasIndividuales.HasValue ?
                new ObjectParameter("CamasIndividuales", camasIndividuales) :
                new ObjectParameter("CamasIndividuales", typeof(int));
    
            var camasMatrimonialesParameter = camasMatrimoniales.HasValue ?
                new ObjectParameter("CamasMatrimoniales", camasMatrimoniales) :
                new ObjectParameter("CamasMatrimoniales", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertHabitacion", estadoParameter, precioParameter, tipoHabitacionParameter, cantidadPersonasParameter, camasIndividualesParameter, camasMatrimonialesParameter, observacionesParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_InsertPrecio(string tipoMoneda, Nullable<decimal> monto)
        {
            var tipoMonedaParameter = tipoMoneda != null ?
                new ObjectParameter("TipoMoneda", tipoMoneda) :
                new ObjectParameter("TipoMoneda", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertPrecio", tipoMonedaParameter, montoParameter);
        }
    
        public virtual int sproc_hoteles_InsertReserva(Nullable<int> estadoReserva_ID_EstadoRes, string cliente_Cedula, Nullable<System.DateTime> fecha)
        {
            var estadoReserva_ID_EstadoResParameter = estadoReserva_ID_EstadoRes.HasValue ?
                new ObjectParameter("EstadoReserva_ID_EstadoRes", estadoReserva_ID_EstadoRes) :
                new ObjectParameter("EstadoReserva_ID_EstadoRes", typeof(int));
    
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertReserva", estadoReserva_ID_EstadoResParameter, cliente_CedulaParameter, fechaParameter);
        }
    
        public virtual int sproc_hoteles_InsertRol(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertRol", descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertRol_Usuario(Nullable<int> rol_ID_Rol, string usuario_Cedula)
        {
            var rol_ID_RolParameter = rol_ID_Rol.HasValue ?
                new ObjectParameter("Rol_ID_Rol", rol_ID_Rol) :
                new ObjectParameter("Rol_ID_Rol", typeof(int));
    
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertRol_Usuario", rol_ID_RolParameter, usuario_CedulaParameter);
        }
    
        public virtual int sproc_hoteles_InsertSB_Tarjeta(Nullable<decimal> numTarjeta, Nullable<decimal> mesExp, Nullable<decimal> yearExp, Nullable<decimal> cVV, Nullable<decimal> monto, string tipo)
        {
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            var mesExpParameter = mesExp.HasValue ?
                new ObjectParameter("MesExp", mesExp) :
                new ObjectParameter("MesExp", typeof(decimal));
    
            var yearExpParameter = yearExp.HasValue ?
                new ObjectParameter("YearExp", yearExp) :
                new ObjectParameter("YearExp", typeof(decimal));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertSB_Tarjeta", numTarjetaParameter, mesExpParameter, yearExpParameter, cVVParameter, montoParameter, tipoParameter);
        }
    
        public virtual int sproc_hoteles_InsertTarjeta(string num_Tarjeta, Nullable<decimal> mes_Exp, Nullable<decimal> year_Exp, Nullable<decimal> cVV, string tipo)
        {
            var num_TarjetaParameter = num_Tarjeta != null ?
                new ObjectParameter("Num_Tarjeta", num_Tarjeta) :
                new ObjectParameter("Num_Tarjeta", typeof(string));
    
            var mes_ExpParameter = mes_Exp.HasValue ?
                new ObjectParameter("Mes_Exp", mes_Exp) :
                new ObjectParameter("Mes_Exp", typeof(decimal));
    
            var year_ExpParameter = year_Exp.HasValue ?
                new ObjectParameter("Year_Exp", year_Exp) :
                new ObjectParameter("Year_Exp", typeof(decimal));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertTarjeta", num_TarjetaParameter, mes_ExpParameter, year_ExpParameter, cVVParameter, tipoParameter);
        }
    
        public virtual int sproc_hoteles_InsertTarjeta_Cliente(string cliente_Cedula, string tarjeta_Num_Tarjeta)
        {
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            var tarjeta_Num_TarjetaParameter = tarjeta_Num_Tarjeta != null ?
                new ObjectParameter("Tarjeta_Num_Tarjeta", tarjeta_Num_Tarjeta) :
                new ObjectParameter("Tarjeta_Num_Tarjeta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertTarjeta_Cliente", cliente_CedulaParameter, tarjeta_Num_TarjetaParameter);
        }
    
        public virtual int sproc_hoteles_InsertTipo_Articulo(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertTipo_Articulo", descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertTipo_Habitacion(string iD_TipoHab, string descripcion)
        {
            var iD_TipoHabParameter = iD_TipoHab != null ?
                new ObjectParameter("ID_TipoHab", iD_TipoHab) :
                new ObjectParameter("ID_TipoHab", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertTipo_Habitacion", iD_TipoHabParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_InsertUsuario(string cedula, string nombre, string primerApellido, string segundoApellido, string correo, string contrasena, string preguntaSeguridad, string respuestaSeguridad)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var preguntaSeguridadParameter = preguntaSeguridad != null ?
                new ObjectParameter("PreguntaSeguridad", preguntaSeguridad) :
                new ObjectParameter("PreguntaSeguridad", typeof(string));
    
            var respuestaSeguridadParameter = respuestaSeguridad != null ?
                new ObjectParameter("RespuestaSeguridad", respuestaSeguridad) :
                new ObjectParameter("RespuestaSeguridad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_InsertUsuario", cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, correoParameter, contrasenaParameter, preguntaSeguridadParameter, respuestaSeguridadParameter);
        }
    
        public virtual ObjectResult<sproc_hoteles_LoginUsuario_Result> sproc_hoteles_LoginUsuario(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_hoteles_LoginUsuario_Result>("sproc_hoteles_LoginUsuario", correoParameter, contrasenaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateActividad(Nullable<int> iD_Actividad, string nombre, string descripcion, Nullable<int> cupo, Nullable<int> espaciosDisponibles, string imagen)
        {
            var iD_ActividadParameter = iD_Actividad.HasValue ?
                new ObjectParameter("ID_Actividad", iD_Actividad) :
                new ObjectParameter("ID_Actividad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var cupoParameter = cupo.HasValue ?
                new ObjectParameter("Cupo", cupo) :
                new ObjectParameter("Cupo", typeof(int));
    
            var espaciosDisponiblesParameter = espaciosDisponibles.HasValue ?
                new ObjectParameter("EspaciosDisponibles", espaciosDisponibles) :
                new ObjectParameter("EspaciosDisponibles", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateActividad", iD_ActividadParameter, nombreParameter, descripcionParameter, cupoParameter, espaciosDisponiblesParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_UpdateArticulo(Nullable<int> iD_Articulo, Nullable<int> precio_ID_Precio, string nombre, string descripcion, Nullable<int> cantidad, Nullable<int> tipo_Articulo_ID_TipoArt, string imagen)
        {
            var iD_ArticuloParameter = iD_Articulo.HasValue ?
                new ObjectParameter("ID_Articulo", iD_Articulo) :
                new ObjectParameter("ID_Articulo", typeof(int));
    
            var precio_ID_PrecioParameter = precio_ID_Precio.HasValue ?
                new ObjectParameter("Precio_ID_Precio", precio_ID_Precio) :
                new ObjectParameter("Precio_ID_Precio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var tipo_Articulo_ID_TipoArtParameter = tipo_Articulo_ID_TipoArt.HasValue ?
                new ObjectParameter("Tipo_Articulo_ID_TipoArt", tipo_Articulo_ID_TipoArt) :
                new ObjectParameter("Tipo_Articulo_ID_TipoArt", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateArticulo", iD_ArticuloParameter, precio_ID_PrecioParameter, nombreParameter, descripcionParameter, cantidadParameter, tipo_Articulo_ID_TipoArtParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_UpdateBitacora(Nullable<int> iD_Cambio, string usuario_Cedula, Nullable<System.DateTime> fecha, string iD_Registro, string tipo, string descripcion, string detalles)
        {
            var iD_CambioParameter = iD_Cambio.HasValue ?
                new ObjectParameter("ID_Cambio", iD_Cambio) :
                new ObjectParameter("ID_Cambio", typeof(int));
    
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var iD_RegistroParameter = iD_Registro != null ?
                new ObjectParameter("ID_Registro", iD_Registro) :
                new ObjectParameter("ID_Registro", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var detallesParameter = detalles != null ?
                new ObjectParameter("Detalles", detalles) :
                new ObjectParameter("Detalles", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateBitacora", iD_CambioParameter, usuario_CedulaParameter, fechaParameter, iD_RegistroParameter, tipoParameter, descripcionParameter, detallesParameter);
        }
    
        public virtual int sproc_hoteles_UpdateCliente(string cedula, Nullable<int> estadoCliente_ID_EstadoCli, string nombre, string primerApellido, string segundoApellido, string correo, string contrasena)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var estadoCliente_ID_EstadoCliParameter = estadoCliente_ID_EstadoCli.HasValue ?
                new ObjectParameter("EstadoCliente_ID_EstadoCli", estadoCliente_ID_EstadoCli) :
                new ObjectParameter("EstadoCliente_ID_EstadoCli", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateCliente", cedulaParameter, estadoCliente_ID_EstadoCliParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, correoParameter, contrasenaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateConsecutivo(Nullable<int> iD_Consecutivo, Nullable<int> num_Consecutivo, Nullable<bool> posee_Prefijo, string prefijo, Nullable<bool> posee_Rango, Nullable<int> rango_Inicial, Nullable<int> rango_Final, string descripcion)
        {
            var iD_ConsecutivoParameter = iD_Consecutivo.HasValue ?
                new ObjectParameter("ID_Consecutivo", iD_Consecutivo) :
                new ObjectParameter("ID_Consecutivo", typeof(int));
    
            var num_ConsecutivoParameter = num_Consecutivo.HasValue ?
                new ObjectParameter("Num_Consecutivo", num_Consecutivo) :
                new ObjectParameter("Num_Consecutivo", typeof(int));
    
            var posee_PrefijoParameter = posee_Prefijo.HasValue ?
                new ObjectParameter("Posee_Prefijo", posee_Prefijo) :
                new ObjectParameter("Posee_Prefijo", typeof(bool));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("Prefijo", prefijo) :
                new ObjectParameter("Prefijo", typeof(string));
    
            var posee_RangoParameter = posee_Rango.HasValue ?
                new ObjectParameter("Posee_Rango", posee_Rango) :
                new ObjectParameter("Posee_Rango", typeof(bool));
    
            var rango_InicialParameter = rango_Inicial.HasValue ?
                new ObjectParameter("Rango_Inicial", rango_Inicial) :
                new ObjectParameter("Rango_Inicial", typeof(int));
    
            var rango_FinalParameter = rango_Final.HasValue ?
                new ObjectParameter("Rango_Final", rango_Final) :
                new ObjectParameter("Rango_Final", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateConsecutivo", iD_ConsecutivoParameter, num_ConsecutivoParameter, posee_PrefijoParameter, prefijoParameter, posee_RangoParameter, rango_InicialParameter, rango_FinalParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateEasyPay(string correoCuenta, Nullable<int> codSeguridad, string contrasena, Nullable<decimal> numTarjeta)
        {
            var correoCuentaParameter = correoCuenta != null ?
                new ObjectParameter("CorreoCuenta", correoCuenta) :
                new ObjectParameter("CorreoCuenta", typeof(string));
    
            var codSeguridadParameter = codSeguridad.HasValue ?
                new ObjectParameter("CodSeguridad", codSeguridad) :
                new ObjectParameter("CodSeguridad", typeof(int));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateEasyPay", correoCuentaParameter, codSeguridadParameter, contrasenaParameter, numTarjetaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateError(Nullable<int> iD_Error, Nullable<System.DateTime> fecha, string descripcion)
        {
            var iD_ErrorParameter = iD_Error.HasValue ?
                new ObjectParameter("ID_Error", iD_Error) :
                new ObjectParameter("ID_Error", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateError", iD_ErrorParameter, fechaParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateEstadoCliente(Nullable<int> iD_EstadoCli, string descripcion)
        {
            var iD_EstadoCliParameter = iD_EstadoCli.HasValue ?
                new ObjectParameter("ID_EstadoCli", iD_EstadoCli) :
                new ObjectParameter("ID_EstadoCli", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateEstadoCliente", iD_EstadoCliParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateEstadoHabitacion(string iD_EstadoHab, string descripcion)
        {
            var iD_EstadoHabParameter = iD_EstadoHab != null ?
                new ObjectParameter("ID_EstadoHab", iD_EstadoHab) :
                new ObjectParameter("ID_EstadoHab", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateEstadoHabitacion", iD_EstadoHabParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateEstadoReserva(Nullable<int> iD_EstadoRes, string descripcion)
        {
            var iD_EstadoResParameter = iD_EstadoRes.HasValue ?
                new ObjectParameter("ID_EstadoRes", iD_EstadoRes) :
                new ObjectParameter("ID_EstadoRes", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateEstadoReserva", iD_EstadoResParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateHabitacion(Nullable<int> iD_Habitacion, string estadoHabitacion, string precio, string tipoHabitacion, Nullable<int> cantidadPersonas, Nullable<int> camasIndividuales, Nullable<int> camasMatrimoniales, string observaciones, string imagen)
        {
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            var estadoHabitacionParameter = estadoHabitacion != null ?
                new ObjectParameter("EstadoHabitacion", estadoHabitacion) :
                new ObjectParameter("EstadoHabitacion", typeof(string));
    
            var precioParameter = precio != null ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(string));
    
            var tipoHabitacionParameter = tipoHabitacion != null ?
                new ObjectParameter("TipoHabitacion", tipoHabitacion) :
                new ObjectParameter("TipoHabitacion", typeof(string));
    
            var cantidadPersonasParameter = cantidadPersonas.HasValue ?
                new ObjectParameter("CantidadPersonas", cantidadPersonas) :
                new ObjectParameter("CantidadPersonas", typeof(int));
    
            var camasIndividualesParameter = camasIndividuales.HasValue ?
                new ObjectParameter("CamasIndividuales", camasIndividuales) :
                new ObjectParameter("CamasIndividuales", typeof(int));
    
            var camasMatrimonialesParameter = camasMatrimoniales.HasValue ?
                new ObjectParameter("CamasMatrimoniales", camasMatrimoniales) :
                new ObjectParameter("CamasMatrimoniales", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateHabitacion", iD_HabitacionParameter, estadoHabitacionParameter, precioParameter, tipoHabitacionParameter, cantidadPersonasParameter, camasIndividualesParameter, camasMatrimonialesParameter, observacionesParameter, imagenParameter);
        }
    
        public virtual int sproc_hoteles_UpdatePrecio(Nullable<int> iD_Precio, string tipo, Nullable<decimal> monto)
        {
            var iD_PrecioParameter = iD_Precio.HasValue ?
                new ObjectParameter("ID_Precio", iD_Precio) :
                new ObjectParameter("ID_Precio", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdatePrecio", iD_PrecioParameter, tipoParameter, montoParameter);
        }
    
        public virtual int sproc_hoteles_UpdateReserva(Nullable<int> iD_Reserva, Nullable<int> estadoReserva_ID_EstadoRes, string cliente_Cedula, Nullable<System.DateTime> fecha)
        {
            var iD_ReservaParameter = iD_Reserva.HasValue ?
                new ObjectParameter("ID_Reserva", iD_Reserva) :
                new ObjectParameter("ID_Reserva", typeof(int));
    
            var estadoReserva_ID_EstadoResParameter = estadoReserva_ID_EstadoRes.HasValue ?
                new ObjectParameter("EstadoReserva_ID_EstadoRes", estadoReserva_ID_EstadoRes) :
                new ObjectParameter("EstadoReserva_ID_EstadoRes", typeof(int));
    
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateReserva", iD_ReservaParameter, estadoReserva_ID_EstadoResParameter, cliente_CedulaParameter, fechaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateRol(Nullable<int> iD_Rol, string descripcion)
        {
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateRol", iD_RolParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateRol_Usuario(Nullable<int> rol_ID_Rol, string usuario_Cedula)
        {
            var rol_ID_RolParameter = rol_ID_Rol.HasValue ?
                new ObjectParameter("Rol_ID_Rol", rol_ID_Rol) :
                new ObjectParameter("Rol_ID_Rol", typeof(int));
    
            var usuario_CedulaParameter = usuario_Cedula != null ?
                new ObjectParameter("Usuario_Cedula", usuario_Cedula) :
                new ObjectParameter("Usuario_Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateRol_Usuario", rol_ID_RolParameter, usuario_CedulaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateSB_Tarjeta(Nullable<decimal> numTarjeta, Nullable<decimal> mesExp, Nullable<decimal> yearExp, Nullable<decimal> cVV, Nullable<decimal> monto, string tipo)
        {
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(decimal));
    
            var mesExpParameter = mesExp.HasValue ?
                new ObjectParameter("MesExp", mesExp) :
                new ObjectParameter("MesExp", typeof(decimal));
    
            var yearExpParameter = yearExp.HasValue ?
                new ObjectParameter("YearExp", yearExp) :
                new ObjectParameter("YearExp", typeof(decimal));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateSB_Tarjeta", numTarjetaParameter, mesExpParameter, yearExpParameter, cVVParameter, montoParameter, tipoParameter);
        }
    
        public virtual int sproc_hoteles_UpdateTarjeta(string num_Tarjeta, Nullable<decimal> mes_Exp, Nullable<decimal> year_Exp, Nullable<decimal> cVV, string tipo)
        {
            var num_TarjetaParameter = num_Tarjeta != null ?
                new ObjectParameter("Num_Tarjeta", num_Tarjeta) :
                new ObjectParameter("Num_Tarjeta", typeof(string));
    
            var mes_ExpParameter = mes_Exp.HasValue ?
                new ObjectParameter("Mes_Exp", mes_Exp) :
                new ObjectParameter("Mes_Exp", typeof(decimal));
    
            var year_ExpParameter = year_Exp.HasValue ?
                new ObjectParameter("Year_Exp", year_Exp) :
                new ObjectParameter("Year_Exp", typeof(decimal));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateTarjeta", num_TarjetaParameter, mes_ExpParameter, year_ExpParameter, cVVParameter, tipoParameter);
        }
    
        public virtual int sproc_hoteles_UpdateTarjeta_Cliente(string cliente_Cedula, string tarjeta_Num_Tarjeta)
        {
            var cliente_CedulaParameter = cliente_Cedula != null ?
                new ObjectParameter("Cliente_Cedula", cliente_Cedula) :
                new ObjectParameter("Cliente_Cedula", typeof(string));
    
            var tarjeta_Num_TarjetaParameter = tarjeta_Num_Tarjeta != null ?
                new ObjectParameter("Tarjeta_Num_Tarjeta", tarjeta_Num_Tarjeta) :
                new ObjectParameter("Tarjeta_Num_Tarjeta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateTarjeta_Cliente", cliente_CedulaParameter, tarjeta_Num_TarjetaParameter);
        }
    
        public virtual int sproc_hoteles_UpdateTipo_Articulo(Nullable<int> iD_TipoArt, string descripcion)
        {
            var iD_TipoArtParameter = iD_TipoArt.HasValue ?
                new ObjectParameter("ID_TipoArt", iD_TipoArt) :
                new ObjectParameter("ID_TipoArt", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateTipo_Articulo", iD_TipoArtParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateTipo_Habitacion(string iD_TipoHab, string descripcion)
        {
            var iD_TipoHabParameter = iD_TipoHab != null ?
                new ObjectParameter("ID_TipoHab", iD_TipoHab) :
                new ObjectParameter("ID_TipoHab", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateTipo_Habitacion", iD_TipoHabParameter, descripcionParameter);
        }
    
        public virtual int sproc_hoteles_UpdateUsuario(string cedula, string nombre, string primerApellido, string segundoApellido, string correo, string contrasena, string preguntaSeguridad, string respuestaSeguridad)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var preguntaSeguridadParameter = preguntaSeguridad != null ?
                new ObjectParameter("PreguntaSeguridad", preguntaSeguridad) :
                new ObjectParameter("PreguntaSeguridad", typeof(string));
    
            var respuestaSeguridadParameter = respuestaSeguridad != null ?
                new ObjectParameter("RespuestaSeguridad", respuestaSeguridad) :
                new ObjectParameter("RespuestaSeguridad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_hoteles_UpdateUsuario", cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, correoParameter, contrasenaParameter, preguntaSeguridadParameter, respuestaSeguridadParameter);
        }
    }
}
