//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.Compras = new HashSet<Compra>();
            this.Habitacions = new HashSet<Habitacion>();
        }
    
        public int ID_Reserva { get; set; }
        public int EstadoReserva_ID_EstadoRes { get; set; }
        public string Cliente_Cedula { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual ICollection<Habitacion> Habitacions { get; set; }
    }
}
