//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Rol_Usuario = new HashSet<Rol_Usuario>();
        }
    
        public int ID_Rol { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Rol_Usuario> Rol_Usuario { get; set; }
    }
}
