//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public Tarjeta()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public string Num_Tarjeta { get; set; }
        public decimal Mes_Exp { get; set; }
        public decimal Year_Exp { get; set; }
        public decimal CVV { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
