//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Articulo
    {
        public Tipo_Articulo()
        {
            this.Articuloes = new HashSet<Articulo>();
        }
    
        public int ID_TipoArt { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Articulo> Articuloes { get; set; }
    }
}
